//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2katmanlimvcapiornekproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public int FirmaNo { get; set; }
        public string FirmaAd { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public string Sektor { get; set; }
    }
}
