//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2katmanlimvcapiornekproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imalatlar
    {
        public int ImalatNo { get; set; }
        public string AnaMadde { get; set; }
        public string YardimciMadde { get; set; }
        public Nullable<decimal> IsciMaliyeti { get; set; }
        public string DigerMaddeler { get; set; }
    }
}
