//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2katmanlimvcapiornekproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apimvccrudEntities : DbContext
    {
        public apimvccrudEntities()
            : base("name=apimvccrudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisanlar> Calisanlars { get; set; }
        public virtual DbSet<Subeler> Subelers { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<Firmalar> Firmalars { get; set; }
        public virtual DbSet<Imalatlar> Imalatlars { get; set; }
        public virtual DbSet<Satilanlar> Satilanlars { get; set; }
    }
}
