//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2katmanlimvcapiornekproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satilanlar
    {
        public int SatilanNo { get; set; }
        public string SatilanUrunAdi { get; set; }
        public Nullable<int> BirimFiyat { get; set; }
        public Nullable<int> Maliyet { get; set; }
    }
}
