//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2katmanlimvcapiornekproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler
    {
        public int SubeNo { get; set; }
        public string SubeAdi { get; set; }
        public string SubeAdres { get; set; }
        public string SubeTelefon { get; set; }
        public string Yetkili { get; set; }
    }
}
